### ISSUE TITLE
授权出现了错误 = =

### ISSUE THREAD

**Issue by AlickH** [iMyon/Music2Lastfm#1]
Invalid API key. If you are a third party developer see our authentication how-to to find out more.

请问要怎样才能解决呢

我用的是 Safari

授权网易云音乐时出现的

**Comment by iMyon** [comment]
更新一下脚本

**Comment by AlickH** [comment]
嗯 可以用了 谢谢

**Comment by AlickH** [comment]
突然发现好像只是在播放时显示 Scrobbling now 播放完了并没有记录上 = =
只有在 last.fm 页面上加红心才会被记录上
请问是什么原因呢
